### ISSUE TITLE
Bug: Tracking Golem continues to control the player's camera after switching to creative mode

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#152]
### What Feature Types Apply to This Bug?

Entity, System

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.64

### The Aether Genesis Version

ee1177d

### Steps to Reproduce

Step 1: Spawn a Tracking golem
Step 2: Switch to Survival Mode
Step 3: Switch to Creative mode
Step 4: notice the tracking golem still controls your camera

### What You Expect To Happen

The tracking golem would no longer control the camera

### What Actually Happened

The tracking golem continued controlling the camera

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The Tracking Golem is pending a full redesign.
