### ISSUE TITLE
Bug: Tracking Golem does not move the camera pitch up and down

### ISSUE THREAD

**Issue by Zepalesque** [The-Aether-Team/The-Aether-Genesis#153]
### What Feature Types Apply to This Bug?

Entity, System

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.64

### The Aether Genesis Version

ee1177d

### Steps to Reproduce

1. Spawn a tracking golem
2. Go into survival mode
3. Notice that the camera does not move up and down to follow the golem, and instead only moves left and right

### What You Expect To Happen

The camera would move up and down to follow the golem

### What Actually Happened

The camera only moved left and right, and was forced into the middle of the screen in terms of up and down

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The Tracking Golem is pending a full redesign.
